apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: movies
  name: movies-deploy                                 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: movies
  template:
    metadata:
      labels:
        app: movies
    spec:
      containers:
      - name: cont1
        image: sohail03/train:latest
        resources:
          limits:
            cpu: "1"
            memory: 400Mi
          requests:
            cpu: "0.25"
            memory: 20Mi
